### ISSUE TITLE
Xterm not working

### ISSUE THREAD

**Issue by mohsenomidi** [PabloLION/xterm-react#29]
Dear @PabloLION ,

Based on Documentation the simple minimum component not working, would you provide the working example
Also the import should be changed to `import { XTerm } from "@pablo-lion/xterm-react";`

Thanks

**Comment by PabloLION** [comment]
yea right. I totally missed that because I was going to name the package "xterm-react". Thanks for the notice!

**Comment by mohsenomidi** [comment]
Thanks, also with this change the provided example not working

**Comment by PabloLION** [comment]
Yes, I checked yesterday and found the problem lies in the lifecycle of the XTerm component. In my initial test case, I only evaluated the use case without strict mode.

I have now added a test case that wraps the component in strict mode tags, and I am addressing the issue.

There are additional missing cases, such as handling multiple instances and input capabilities. I will add these later.

**Comment by mohsenomidi** [comment]
Sounds great, thanks

**Comment by PabloLION** [comment]
solved by #30

**Comment by PabloLION** [comment]
@mohsenomidi can you check https://replit.com/@PabloLION/XTerm-React?v=1 and see if this is what you wanted?

**Comment by mohsenomidi** [comment]
Thanks, It's okay now
Sorry for late response
